name: Spell Checker
description: Check and Annotate files with spelling suggestions to improve your spelling
author: bubkoo <bubkoo.wy@gmail.com>
runs:
  using: node16
  main: dist/index.js
branding:
  icon: file-text
  color: orange
inputs:
  GITHUB_TOKEN:
    description: Your GitHub token for authentication
    required: true
  include:
    description: File patterns to match checked files
    required: false
  exclude:
    description: File patterns to exclude files match checked files
    required: false
  markdown-spellcheck:
    required: false
  write-good:
    required: false
  alex:
    required: false
